### PR TITLE
Profiles: Add policy efforts

### PR DESCRIPTION
**Pull request by finnwoelm-sdsn**
Display policy efforts for the 47 countries covered by the SDSN survey on government efforts for the SDGs.

### CODE REVIEW

**Comment by finnwoelm-sdsn** [comment]
Countries covered:

image

**Comment by finnwoelm-sdsn** [comment]
Example: https://deploy-preview-33--sdr-twenty-one.netlify.app/profiles/france/policy-efforts

**Review by DonTouzi — APPROVED** [review]
@finnwoelm-sdsn, everything's ok, awesome work :+1:

**Review by Sakala85 — APPROVED** [review]

**Comment by Sakala85** [comment]
> Display policy efforts for the 47 countries covered by the SDSN survey on government efforts for the SDGs.



> Example: https://deploy-preview-33--sdr-twenty-one.netlify.app/profiles/france/policy-efforts

Amazing! 👍  Yes can merge @FinnWoelm

**Pull request merged**
