### PR TITLE
Add chapter/part 2

### PR DESCRIPTION
**Pull request by finnwoelm-sdsn**
Add text, figures, and tables for part 2 of the report.

### CODE REVIEW

**Comment by finnwoelm-sdsn** [comment]
Same as with part 1: If you could take a careful look to make sure that a) no text is missing and b) I put the correct figures, that would be great 😁

**Comment by DonTouzi** [comment]
> Same as with part 1: If you could take a careful look to make sure that a) no text is missing and b) I put the correct figures, that would be great grin

Ok, i will check now :)

**Comment by DonTouzi** [comment]
@FinnWoelm, everything is great, I have some remarks : 
1) 2.1 The 2021 SDG Index : the first paragraph have a line break (way to ...)
2) 2.5 The SDG dashboards : i think in the report Oceania comes after Sub‑Saharan Africa
3) for example :  COVID-19 has increased hunger and food insecurity in many parts of the world (Fan, 2020; FAO, 2021; WFP, 2020). it's a quote it should be in emphasis ?

**Comment by finnwoelm-sdsn** [comment]
1. Thank you! Good catch on 2.1 paragraph break! Just fixed 🚑

2. Yes, true! I decided to change the order, so that the figures are in the correct order. Figure 2.25 for Oceania comes before 2.26 for sub-Saharan Africa, so I followed the same order in the text, also :)
image

3. No, should be OK. Only if the text in the PDF is in emphasis/italics, then it should be in emphasis/italics in the website also.

Thank you for the careful review 😊

**Comment by finnwoelm-sdsn** [comment]
PS: @FinnWoelm is my personal GitHub username. My SDSN one is @finnwoelm-sdsn 😁 When you tag @FinnWoelm, the email notifications go to my personal account and email inbox 😁

**Comment by DonTouzi** [comment]
> PS: @FinnWoelm is my personal GitHub username. My SDSN one is @finnwoelm-sdsn grin When you tag @FinnWoelm, the email notifications go to my personal account and email inbox grin

Ok :p

**Review by DonTouzi — APPROVED** [review]

**Comment by finnwoelm-sdsn** [comment]
Merci 😊

**Pull request merged**
