### PR TITLE
Fix Next.js fast refresh on Windows

### PR DESCRIPTION
**Pull request by finnwoelm-sdsn**
Fast refresh (which relies on Server Sent Events) only works on Windows 
when the host is the default unspecified IPv6 host (::). Next.js 
defaults to the default unspecified IPv4 host (0.0.0.0), but that is not 
compatible with fast refresh on Windows. We use run-script-os to define 
a different `npm run dev` command for Windows with the IPv6 host.

For details, see: 
https://github.com/vercel/next.js/discussions/22214#discussioncomment-795047

### CODE REVIEW

**Comment by finnwoelm-sdsn** [comment]
@DonTouzi — can you fetch this branch onto your computer and check that this correctly runs `next dev`? 


```bash
git fetch
git checkout fix-fast-refresh-on-windows
npm run dev
```

For example, on Windows, it runs `next dev -H ::`, but on non-Windows it should continue to run `next dev`

image

(The parts in red should be different on your computer)

**Comment by DonTouzi** [comment]
> ```shell
> git checkout fix-fast-refresh-on-windows
> ```
@FinnWoelm, for me the (run-script-os) doesn't work !
issue

**Comment by finnwoelm-sdsn** [comment]
Oops, sorry, I forgot one step: Run `npm install` after the `git checkout`.

I added a new package.

**Review by DonTouzi — APPROVED** [review]
it works perfectly :)

**Pull request merged**
