### PR TITLE
Add chapter/part 3

### PR DESCRIPTION
**Pull request by finnwoelm-sdsn**
Add part 3 of the report

### CODE REVIEW

**Comment by finnwoelm-sdsn** [comment]
Here comes part 3! 😊

(One more to go 😁)

**Review by DonTouzi — CHANGES_REQUESTED** [review]
@finnwoelm-sdsn, every things is perfect, just in section 3.2, paragraph 4 has a line break, great job :)

**Comment by finnwoelm-sdsn** [comment]
> 
> 
> @finnwoelm-sdsn, every things is perfect, just in section 3.2, paragraph 4 has a line break, great job :)

Wow, very good catch!!! 🙏

**Comment by DonTouzi** [comment]
i Think you can merge :)

**Pull request merged**
